/**
 * Shoe size conversion table for various regional standards.
 * Provides a comprehensive mapping of shoe sizes across different standarts, including:
 * European (EUR), Mondo (sports shoe metric sizing), UK, US Men's, US Women's,
 * Australian Men's, and Australian Women's sizes.
 * Each object in the table represents a specific shoe size, enabling cross-standard conversion.
 *
 * @typedef {Object} ShoeSize
 * @property {number} eur_shoe_size - European shoe size.
 * @property {number} mondo_shoe_size - Mondo point size, measured in millimeters.
 * @property {number} uk_shoe_size - UK shoe size.
 * @property {number} us_men_shoe_size - US men's shoe size.
 * @property {number} us_women_shoe_size: - US women's shoe size.
 * @property {number} aus_men_shoe_size - Australian men's shoe size.
 * @property {number} aus_women_shoe_size - Australian women's shoe size.
 *
 * @type {ShoeSize[]}
 */
export const shoeSizeConversionTable = [
    {
        eur_shoe_size: 34,
        mondo_shoe_size: 215,
        uk_shoe_size: 2,
        us_men_shoe_size: 3,
        us_women_shoe_size: 4,
        aus_men_shoe_size: 2,
        aus_women_shoe_size: 4,
    },
    {
        eur_shoe_size: 34.5,
        mondo_shoe_size: 215,
        uk_shoe_size: 2.5,
        us_men_shoe_size: 3.5,
        us_women_shoe_size: 4.5,
        aus_men_shoe_size: 2.5,
        aus_women_shoe_size: 4.5,
    },
    {
        eur_shoe_size: 35,
        mondo_shoe_size: 220,
        uk_shoe_size: 3,
        us_men_shoe_size: 4,
        us_women_shoe_size: 5,
        aus_men_shoe_size: 3,
        aus_women_shoe_size: 5,
    },
    {
        eur_shoe_size: 35.5,
        mondo_shoe_size: 225,
        uk_shoe_size: 3.5,
        us_men_shoe_size: 4.5,
        us_women_shoe_size: 5.5,
        aus_men_shoe_size: 3.5,
        aus_women_shoe_size: 5.5,
    },
    {
        eur_shoe_size: 36,
        mondo_shoe_size: 225,
        uk_shoe_size: 4,
        us_men_shoe_size: 5,
        us_women_shoe_size: 6,
        aus_men_shoe_size: 4,
        aus_women_shoe_size: 6,
    },
    {
        eur_shoe_size: 36.5,
        mondo_shoe_size: 230,
        uk_shoe_size: 4,
        us_men_shoe_size: 5,
        us_women_shoe_size: 6,
        aus_men_shoe_size: 4,
        aus_women_shoe_size: 6,
    },
    {
        eur_shoe_size: 37,
        mondo_shoe_size: 235,
        uk_shoe_size: 4.5,
        us_men_shoe_size: 5.5,
        us_women_shoe_size: 6.5,
        aus_men_shoe_size: 4.5,
        aus_women_shoe_size: 6.5,
    },
    {
        eur_shoe_size: 37.5,
        mondo_shoe_size: 235,
        uk_shoe_size: 5,
        us_men_shoe_size: 6,
        us_women_shoe_size: 7,
        aus_men_shoe_size: 5,
        aus_women_shoe_size: 7,
    },
    {
        eur_shoe_size: 38,
        mondo_shoe_size: 245,
        uk_shoe_size: 5.5,
        us_men_shoe_size: 6.5,
        us_women_shoe_size: 7.5,
        aus_men_shoe_size: 5.5,
        aus_women_shoe_size: 7.5,
    },
    {
        eur_shoe_size: 38.5,
        mondo_shoe_size: 245,
        uk_shoe_size: 6,
        us_men_shoe_size: 7,
        us_women_shoe_size: 8,
        aus_men_shoe_size: 6,
        aus_women_shoe_size: 8,
    },
    {
        eur_shoe_size: 39,
        mondo_shoe_size: 245,
        uk_shoe_size: 6,
        us_men_shoe_size: 7,
        us_women_shoe_size: 8,
        aus_men_shoe_size: 6,
        aus_women_shoe_size: 8,
    },
    {
        eur_shoe_size: 39.5,
        mondo_shoe_size: 250,
        uk_shoe_size: 6.5,
        us_men_shoe_size: 7.5,
        us_women_shoe_size: 8.5,
        aus_men_shoe_size: 6.5,
        aus_women_shoe_size: 8.5,
    },
    {
        eur_shoe_size: 40,
        mondo_shoe_size: 255,
        uk_shoe_size: 7,
        us_men_shoe_size: 8,
        us_women_shoe_size: 9,
        aus_men_shoe_size: 7,
        aus_women_shoe_size: 9,
    },
    {
        eur_shoe_size: 40.5,
        mondo_shoe_size: 255,
        uk_shoe_size: 7.5,
        us_men_shoe_size: 8.5,
        us_women_shoe_size: 9.5,
        aus_men_shoe_size: 7.5,
        aus_women_shoe_size: 9.5,
    },
    {
        eur_shoe_size: 41,
        mondo_shoe_size: 260,
        uk_shoe_size: 7.5,
        us_men_shoe_size: 8.5,
        us_women_shoe_size: 9.5,
        aus_men_shoe_size: 7.5,
        aus_women_shoe_size: 9.5,
    },
    {
        eur_shoe_size: 41.5,
        mondo_shoe_size: 265,
        uk_shoe_size: 8,
        us_men_shoe_size: 9,
        us_women_shoe_size: 10,
        aus_men_shoe_size: 8,
        aus_women_shoe_size: 10,
    },
    {
        eur_shoe_size: 42,
        mondo_shoe_size: 265,
        uk_shoe_size: 8.5,
        us_men_shoe_size: 9.5,
        us_women_shoe_size: 10.5,
        aus_men_shoe_size: 8.5,
        aus_women_shoe_size: 10.5,
    },
    {
        eur_shoe_size: 42.5,
        mondo_shoe_size: 270,
        uk_shoe_size: 9,
        us_men_shoe_size: 10,
        us_women_shoe_size: 11,
        aus_men_shoe_size: 9,
        aus_women_shoe_size: 11,
    },
    {
        eur_shoe_size: 43,
        mondo_shoe_size: 275,
        uk_shoe_size: 9.5,
        us_men_shoe_size: 10.5,
        us_women_shoe_size: 11.5,
        aus_men_shoe_size: 9.5,
        aus_women_shoe_size: 11.5,
    },
    {
        eur_shoe_size: 43.5,
        mondo_shoe_size: 275,
        uk_shoe_size: 9.5,
        us_men_shoe_size: 10.5,
        us_women_shoe_size: 11.5,
        aus_men_shoe_size: 9.5,
        aus_women_shoe_size: 11.5,
    },
    {
        eur_shoe_size: 44,
        mondo_shoe_size: 280,
        uk_shoe_size: 10,
        us_men_shoe_size: 11,
        us_women_shoe_size: 12,
        aus_men_shoe_size: 10,
        aus_women_shoe_size: 12,
    },
    {
        eur_shoe_size: 44.5,
        mondo_shoe_size: 285,
        uk_shoe_size: 10.5,
        us_men_shoe_size: 11.5,
        us_women_shoe_size: 12.5,
        aus_men_shoe_size: 10.5,
        aus_women_shoe_size: 12.5,
    },
    {
        eur_shoe_size: 45,
        mondo_shoe_size: 285,
        uk_shoe_size: 11,
        us_men_shoe_size: 12,
        us_women_shoe_size: 13,
        aus_men_shoe_size: 11,
        aus_women_shoe_size: 13,
    },
    {
        eur_shoe_size: 45.5,
        mondo_shoe_size: 290,
        uk_shoe_size: 11.5,
        us_men_shoe_size: 12.5,
        us_women_shoe_size: 13.5,
        aus_men_shoe_size: 11.5,
        aus_women_shoe_size: 13.5,
    },
    {
        eur_shoe_size: 46,
        mondo_shoe_size: 295,
        uk_shoe_size: 11.5,
        us_men_shoe_size: 12.5,
        us_women_shoe_size: 13.5,
        aus_men_shoe_size: 11.5,
        aus_women_shoe_size: 13.5,
    },
    {
        eur_shoe_size: 46.5,
        mondo_shoe_size: 295,
        uk_shoe_size: 12,
        us_men_shoe_size: 13,
        us_women_shoe_size: 14,
        aus_men_shoe_size: 12,
        aus_women_shoe_size: 14,
    },
    {
        eur_shoe_size: 47,
        mondo_shoe_size: 300,
        uk_shoe_size: 12.5,
        us_men_shoe_size: 13.5,
        us_women_shoe_size: 14.5,
        aus_men_shoe_size: 12.5,
        aus_women_shoe_size: 14.5,
    },
    {
        eur_shoe_size: 47.5,
        mondo_shoe_size: 305,
        uk_shoe_size: 13,
        us_men_shoe_size: 14,
        us_women_shoe_size: 15,
        aus_men_shoe_size: 13,
        aus_women_shoe_size: 15,
    },
    {
        eur_shoe_size: 48,
        mondo_shoe_size: 305,
        uk_shoe_size: 13,
        us_men_shoe_size: 14,
        us_women_shoe_size: 15,
        aus_men_shoe_size: 13,
        aus_women_shoe_size: 15,
    },
    {
        eur_shoe_size: 48.5,
        mondo_shoe_size: 310,
        uk_shoe_size: 13.5,
        us_men_shoe_size: 14.5,
        us_women_shoe_size: 15.5,
        aus_men_shoe_size: 13.5,
        aus_women_shoe_size: 15.5,
    },
    {
        eur_shoe_size: 49,
        mondo_shoe_size: 315,
        uk_shoe_size: 14,
        us_men_shoe_size: 15,
        us_women_shoe_size: 16,
        aus_men_shoe_size: 14,
        aus_women_shoe_size: 16,
    },
    {
        eur_shoe_size: 49.5,
        mondo_shoe_size: 315,
        uk_shoe_size: 14.5,
        us_men_shoe_size: 15.5,
        us_women_shoe_size: 16.5,
        aus_men_shoe_size: 14.5,
        aus_women_shoe_size: 16.5,
    },
    {
        eur_shoe_size: 50,
        mondo_shoe_size: 320,
        uk_shoe_size: 15,
        us_men_shoe_size: 16,
        us_women_shoe_size: 17,
        aus_men_shoe_size: 15,
        aus_women_shoe_size: 17,
    },
];
